'use client';
import type { UserProfile } from './data';

export const mockProfiles: UserProfile[] = [
  {
    id: 'mock-1',
    name: 'Aslı',
    firstName: 'Aslı',
    lastName: 'Yılmaz',
    age: 24,
    bio: 'Kahve ve sanat tutkunu. Şehirde yeni yerler keşfetmeyi severim.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1557053910-d9eadeed1c58?w=500', 'https://images.unsplash.com/photo-1659892603525-cf7845582784?w=500'],
    interests: ['art', 'travel', 'coffee'],
    distance: 5,
    email: 'asli@example.com',
    prompts: [],
    zodiac: 'Leo',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-2',
    name: 'Ebru',
    firstName: 'Ebru',
    lastName: 'Kaya',
    age: 27,
    bio: 'Hafta sonları doğa yürüyüşü yapmayı ve yeni tarifler denemeyi severim. Sakin bir akşamda film izlemek gibisi yok.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500', 'https://images.unsplash.com/photo-1532347922424-c652d9b7208e?w=500'],
    interests: ['hiking', 'cooking', 'movies'],
    distance: 5,
    email: 'ebru@example.com',
    prompts: [],
    zodiac: 'Aries',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-3',
    name: 'Ceren',
    firstName: 'Ceren',
    lastName: 'Demir',
    age: 22,
    bio: 'Müzik ruhun gıdasıdır. Konserlere gitmeyi ve gitar çalmayı çok severim.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1526835746352-0b9da4054862?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1526835746352-0b9da4054862?w=500'],
    interests: ['music', 'gaming', 'dancing'],
    distance: 5,
    email: 'ceren@example.com',
    prompts: [],
    zodiac: 'Pisces',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-4',
    name: 'Selin',
    firstName: 'Selin',
    lastName: 'Çelik',
    age: 29,
    bio: 'Yoga ve meditasyon hayatımın bir parçası. Sağlıklı yaşam ve pozitif enerji benim için önemli.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1599558454048-6a546d15b55b?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1599558454048-6a546d15b55b?w=500'],
    interests: ['yoga', 'fitness', 'reading'],
    distance: 5,
    email: 'selin@example.com',
    prompts: [],
    zodiac: 'Libra',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-5',
    name: 'Zeynep',
    firstName: 'Zeynep',
    lastName: 'Arslan',
    age: 26,
    bio: 'Hayvanları çok seviyorum, özellikle kedileri. Boş zamanlarımda fotoğraf çekiyorum.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1611601322175-87594859b079?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1611601322175-87594859b079?w=500'],
    interests: ['photography', 'volunteering', 'movies'],
    distance: 5,
    email: 'zeynep@example.com',
    prompts: [],
    zodiac: 'Cancer',
    location: 'İstanbul, TR'
  },
    {
    id: 'mock-6',
    name: 'İrem',
    firstName: 'İrem',
    lastName: 'Doğan',
    age: 23,
    bio: 'Modayı yakından takip ederim. Alışveriş yapmak ve yeni stiller denemek en büyük hobim.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500'],
    interests: ['fashion', 'travel', 'dancing'],
    distance: 5,
    email: 'irem@example.com',
    prompts: [],
    zodiac: 'Taurus',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-7',
    name: 'Gamze',
    firstName: 'Gamze',
    lastName: 'Öztürk',
    age: 28,
    bio: 'Bilgisayar oyunları ve e-spor tutkunuyum. Birlikte oynayacak birini arıyorum.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500'],
    interests: ['gaming', 'technology', 'movies'],
    distance: 5,
    email: 'gamze@example.com',
    prompts: [],
    zodiac: 'Scorpio',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-8',
    name: 'Elif',
    firstName: 'Elif',
    lastName: 'Aydın',
    age: 25,
    bio: 'Tiyatro ve sinemaya bayılırım. Her hafta mutlaka bir oyuna veya filme giderim.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1619895862022-09114b41f16f?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1619895862022-09114b41f16f?w=500'],
    interests: ['theater', 'movies', 'reading'],
    distance: 5,
    email: 'elif@example.com',
    prompts: [],
    zodiac: 'Gemini',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-9',
    name: 'Büşra',
    firstName: 'Büşra',
    lastName: 'Koç',
    age: 30,
    bio: 'Spor hayatımın merkezinde. Koşmayı, yüzmeyi ve fitness yapmayı seviyorum.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500'],
    interests: ['sports', 'fitness', 'hiking'],
    distance: 5,
    email: 'busra@example.com',
    prompts: [],
    zodiac: 'Virgo',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-10',
    name: 'Merve',
    firstName: 'Merve',
    lastName: 'Şahin',
    age: 21,
    bio: 'Yeni yerler görmek, yeni kültürler tanımak en büyük tutkum. Bir sonraki durağım neresi olacak acaba?',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1552695845-4a0237de1536?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1552695845-4a0237de1536?w=500'],
    interests: ['travel', 'photography', 'cooking'],
    distance: 5,
    email: 'merve@example.com',
    prompts: [],
    zodiac: 'Sagittarius',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-11',
    name: 'Fatma',
    firstName: 'Fatma',
    lastName: 'Yıldız',
    age: 26,
    bio: 'Evde sakin bir akşamı, güzel bir kitap ve bir fincan çayla geçirmeyi severim.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1562572159-4efc207f5aff?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1562572159-4efc207f5aff?w=500'],
    interests: ['reading', 'cooking', 'yoga'],
    distance: 5,
    email: 'fatma@example.com',
    prompts: [],
    zodiac: 'Aquarius',
    location: 'İstanbul, TR'
  },
  {
    id: 'mock-12',
    name: 'Ayşe',
    firstName: 'Ayşe',
    lastName: 'Polat',
    age: 27,
    bio: 'Hafta sonları kamp yapmayı ve yıldızların altında uyumayı seviyorum.',
    gender: 'woman',
    avatarUrl: 'https://images.unsplash.com/photo-1531123414780-f74242c2b052?w=500',
    imageUrls: ['https://images.unsplash.com/photo-1531123414780-f74242c2b052?w=500'],
    interests: ['camping', 'hiking', 'photography'],
    distance: 5,
    email: 'ayse@example.com',
    prompts: [],
    zodiac: 'Capricorn',
    location: 'İstanbul, TR'
  }
];
